# Generated by Django 4.2.13 on 2024-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('AuthorOne', models.CharField(max_length=20, null=True)),
                ('AuthorTwo', models.CharField(max_length=20, null=True)),
                ('AuthorThree', models.CharField(max_length=20, null=True)),
                ('AuthorFour', models.CharField(max_length=20, null=True)),
                ('AuthorFive', models.CharField(max_length=20, null=True)),
                ('AuthorSix', models.CharField(max_length=20, null=True)),
                ('AuthorSeven', models.CharField(max_length=20, null=True)),
                ('AuthorEight', models.CharField(max_length=20, null=True)),
                ('AuthorNine', models.CharField(max_length=20, null=True)),
                ('AuthorTen', models.CharField(max_length=20, null=True)),
                ('Sources', models.TextField()),
                ('PublishedYears', models.CharField(max_length=10)),
                ('Doi', models.CharField(max_length=100)),
                ('Abstracts', models.TextField()),
            ],
        ),
    ]
