# Generated by Django 4.2.13 on 2024-05-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationDatasets',
        ),
    ]
