# Generated by Django 4.2.13 on 2024-05-31 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationDatasets',
        ),
    ]
