# Generated by Django 4.2.13 on 2024-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0004_delete_publicationdatasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('IdName', models.TextField()),
                ('Citation', models.CharField(max_length=10)),
                ('AuthorOne', models.CharField(max_length=50, null=True)),
                ('AuthorTwo', models.CharField(max_length=50, null=True)),
                ('AuthorThree', models.CharField(max_length=50, null=True)),
                ('AuthorFour', models.CharField(max_length=50, null=True)),
                ('AuthorFive', models.CharField(max_length=50, null=True)),
                ('AuthorSix', models.CharField(max_length=50, null=True)),
                ('AuthorSeven', models.CharField(max_length=50, null=True)),
                ('AuthorEight', models.CharField(max_length=50, null=True)),
                ('AuthorNine', models.CharField(max_length=50, null=True)),
                ('AuthorTen', models.CharField(max_length=50, null=True)),
                ('Sources', models.TextField()),
                ('PublishedYears', models.CharField(max_length=10)),
                ('Doi', models.CharField(max_length=100)),
                ('Abstracts', models.TextField()),
            ],
        ),
    ]
