# Generated by Django 4.2.13 on 2024-06-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationDatasets',
        ),
    ]
