# Generated by Django 4.2.13 on 2024-06-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationDatasets',
        ),
    ]
